BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[GUARD_MASTER] (
    [Guard_Id] INT NOT NULL IDENTITY(1,1),
    [Name] VARCHAR(100) NOT NULL,
    [Mobile] VARCHAR(15) NOT NULL,
    [Active] BIT NOT NULL CONSTRAINT [GUARD_MASTER_Active_df] DEFAULT 1,
    [Created_At] DATETIME2 NOT NULL CONSTRAINT [GUARD_MASTER_Created_At_df] DEFAULT CURRENT_TIMESTAMP,
    [Updated_At] DATETIME2 NOT NULL,
    CONSTRAINT [GUARD_MASTER_pkey] PRIMARY KEY CLUSTERED ([Guard_Id])
);

-- CreateTable
CREATE TABLE [dbo].[DRIVER_CHECKIN] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Do_No] VARCHAR(50) NOT NULL,
    [Vehicle_No] VARCHAR(20) NOT NULL,
    [Driver_Name] VARCHAR(100) NOT NULL,
    [Mobile] VARCHAR(15) NOT NULL,
    [Licence_Expiry_Date] DATE,
    [Insurance_Number] VARCHAR(50),
    [Insurance_Expiry_Date] DATE,
    [Chassis_Number] VARCHAR(50),
    [Rc_Expiry_Date] DATE,
    [Fitness_Expiry_Date] DATE,
    [Status] VARCHAR(20) NOT NULL CONSTRAINT [DRIVER_CHECKIN_Status_df] DEFAULT 'Pending',
    [Zgp] VARCHAR(50),
    [Entry_Time] DATETIME2,
    [Exit_Time] DATETIME2,
    [Latitude] DECIMAL(10,6),
    [Longitude] DECIMAL(10,6),
    [Token] VARCHAR(50),
    [Created_At] DATETIME2 NOT NULL CONSTRAINT [DRIVER_CHECKIN_Created_At_df] DEFAULT CURRENT_TIMESTAMP,
    [Updated_At] DATETIME2 NOT NULL,
    CONSTRAINT [DRIVER_CHECKIN_pkey] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [DRIVER_CHECKIN_Token_key] UNIQUE NONCLUSTERED ([Token])
);

-- CreateTable
CREATE TABLE [dbo].[DRIVER_DOCUMENTS] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Driver_Checkin_Id] INT NOT NULL,
    [Doc_Type] VARCHAR(50) NOT NULL,
    [Expiry_Date] DATE,
    [Verified] BIT NOT NULL CONSTRAINT [DRIVER_DOCUMENTS_Verified_df] DEFAULT 0,
    [Image_Path] VARCHAR(255) NOT NULL,
    [Verified_By] INT,
    [Created_At] DATETIME2 NOT NULL CONSTRAINT [DRIVER_DOCUMENTS_Created_At_df] DEFAULT CURRENT_TIMESTAMP,
    [Updated_At] DATETIME2 NOT NULL,
    CONSTRAINT [DRIVER_DOCUMENTS_pkey] PRIMARY KEY CLUSTERED ([Id])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [DRIVER_CHECKIN_Do_No_idx] ON [dbo].[DRIVER_CHECKIN]([Do_No]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [DRIVER_CHECKIN_Vehicle_No_idx] ON [dbo].[DRIVER_CHECKIN]([Vehicle_No]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [DRIVER_CHECKIN_Status_idx] ON [dbo].[DRIVER_CHECKIN]([Status]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [DRIVER_CHECKIN_Token_idx] ON [dbo].[DRIVER_CHECKIN]([Token]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [DRIVER_DOCUMENTS_Driver_Checkin_Id_idx] ON [dbo].[DRIVER_DOCUMENTS]([Driver_Checkin_Id]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [DRIVER_DOCUMENTS_Verified_By_idx] ON [dbo].[DRIVER_DOCUMENTS]([Verified_By]);

-- AddForeignKey
ALTER TABLE [dbo].[DRIVER_DOCUMENTS] ADD CONSTRAINT [DRIVER_DOCUMENTS_Driver_Checkin_Id_fkey] FOREIGN KEY ([Driver_Checkin_Id]) REFERENCES [dbo].[DRIVER_CHECKIN]([Id]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[DRIVER_DOCUMENTS] ADD CONSTRAINT [DRIVER_DOCUMENTS_Verified_By_fkey] FOREIGN KEY ([Verified_By]) REFERENCES [dbo].[GUARD_MASTER]([Guard_Id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
