CREATE TABLE `DRIVER_CHECKIN_CLAIM` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Do_No` VARCHAR(191) NOT NULL,
    `Session_Id` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `DRIVER_CHECKIN_CLAIM_Do_No_key`(`Do_No`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
